server:
  port: 8443
  servlet:
    session:
      cookie:
        max-age: 1800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 被sql.init.mode替代
    # initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema-all.sql
      data-locations: classpath*:data-all.sql

  devtools:
    restart:
      enabled: true

file:
  baseurl: http://localhost:8443/file/
  folder: /home/yanjing/图片/tmp/