server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # 如果配置了logging.level，这里要设置为false，不然会输出双份的sql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_insert: true
        order_updates: true
        jdbc:
          batch_versioned_data: true
          batch_size: 100
        format_sql: true
        generate_statistics: true

logging:
  level:
    org:
      hibernate:
#        注意这是大写的SQL（logger的类名）
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: trace
