spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql7794818
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.yanjing.entity
  mapper-locations: classpath:mybatis/mapper/*.xml